### PR TITLE
Change to lib folder

### PR DESCRIPTION
**Pull request by Basharfrancis**
Use lib instead of build

### CODE REVIEW

**Review by jamie3 — CHANGES_REQUESTED** [review]
Our standard practise is to use build. Why are we changing it?

**Comment by jamie3** [comment]
Ok sounds good. Was there documentation you found online for this?

**Comment by Basharfrancis** [comment]
> Ok sounds good. Was there documentation you found online for this?

yes, I follow this two docs
https://itnext.io/step-by-step-building-and-publishing-an-npm-typescript-package-44fe7164964c
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by jamie3** [comment]
Excellent

**Pull request merged**
